Repository google/gapid, pull requests merged in 2019-06, with the labels that each got.

#2789 Automatically unlock device screen when possible
  core/os/android/adb/adb_data_test.go
  core/os/android/adb/screen.go
  core/os/android/adb/screen_test.go
  core/os/android/device.go
  core/os/android/keycodes.proto
  gapii/client/adb.go
  gapis/perfetto/android/trace.go
  gapis/trace/android/trace.go
Labels: cla: yes

#2793 Don't try to update an already disposed progress dialog.
  gapic/src/main/com/google/gapid/views/TracerDialog.java
Labels: cla: yes

#2798 Fix a broken link in the README file.
  README.md
Labels: cla: yes

#2796 Add GAPIT auto-generated docs to gapid.dev page
  GAPIT.md
Labels: cla: yes

#2799 Fix broken HDPI handling in image loading.
  gapic/src/main/com/google/gapid/widgets/Theme.java
Labels: cla: yes

#2802 Fix command list table generation
  GAPIT.md
Labels: cla: yes

#2788 Fix for descriptors if we cannot parse the SPIR-V module.
  gapis/api/vulkan/state_rebuilder.go
Labels: cla: yes

#2803 Fix screen unlock: make no assumption about screen lock state change
  core/os/android/adb/screen.go
Labels: cla: yes

#2778 Change the query timestamps RPC to streaming RPC
  cmd/gapit/profile.go
  gapir/README.md
  gapir/cc/android/asset_replay_service.h
  gapir/cc/archive_replay_service.h
  gapir/cc/context.cpp
  gapir/cc/context.h
  gapir/cc/context_test.cpp
  gapir/cc/grpc_replay_service.cpp
  gapir/cc/grpc_replay_service.h
  gapir/cc/interpreter.cpp
  gapir/cc/interpreter.h
  gapir/cc/mock_replay_service.h
  gapir/cc/replay_service.h
  gapir/replay_service/service.proto
  gapir/replay_service/vm.h
  gapis/api/vulkan/BUILD.bazel
  gapis/api/vulkan/find_issues.go
  gapis/api/vulkan/query_timestamps.go
  gapis/api/vulkan/replay.go
  gapis/client/client.go
  gapis/replay/asm/instructions.go
  gapis/replay/builder/builder.go
  gapis/replay/interfaces.go
  gapis/replay/opcode/opcodes.go
  gapis/replay/protocol/opcode.go
  gapis/replay/timestamps.go
  gapis/server/export_replay.go
  gapis/server/grpc.go
  gapis/server/server.go
  gapis/service/service.go
  gapis/service/service.proto
Labels: cla: yes

#2820 Unzip the NDK quietly.
  kokoro/linux/build.sh
Labels: cla: yes

#2790 Auto-generate docs for GAPIT
  README.md
  cmd/gapit/BUILD.bazel
  cmd/gapit/flags.go
  cmd/gapit/make_doc.go
  core/app/help.go
Labels: cla: yes

#2752 Make two UI modifications in Welcoming window and Help-About dialog.
  gapic/res/icons/add.png
  gapic/res/icons/add@2x.png
  gapic/res/icons/clipboard.png
  gapic/res/icons/clipboard@2x.png
  gapic/res/icons/help.png
  gapic/res/icons/help@2x.png
  gapic/res/icons/open.png
  gapic/res/icons/open@2x.png
  gapic/res/icons/recent.png
  gapic/res/icons/recent@2x.png
  gapic/src/main/com/google/gapid/LoadingScreen.java
  gapic/src/main/com/google/gapid/Main.java
  gapic/src/main/com/google/gapid/MainWindow.java
  gapic/src/main/com/google/gapid/views/AboutDialog.java
  gapic/src/main/com/google/gapid/widgets/CopyPaste.java
  gapic/src/main/com/google/gapid/widgets/Theme.java
Labels: cla: yes

#2824 Grab all of `dumpsys window` to determine screen state.
  core/os/android/adb/screen.go
Labels: cla: yes

#2825 Add Perfetto tracing support to gapit.
  cmd/gapit/BUILD.bazel
  cmd/gapit/flags.go
  cmd/gapit/trace.go
Labels: cla: yes

#2829 Some small fixes for when HostOS != Perfetto Trace OS.
  core/app/layout/layout.go
  core/os/device/remotessh/commands.go
Labels: cla: yes

#2821 Update to latest version of Perfetto.
  gapis/perfetto/cc/processor.cpp
  tools/build/third_party/perfetto.bzl
  tools/build/third_party/perfetto/perfetto.BUILD
  tools/build/third_party/perfetto/sqlite.BUILD
Labels: cla: yes

#2837 Bump the version to 1.7.0.
  version.bzl
Labels: cla: yes

#2840 Make Android Perfetto tracing work on Windows.
  core/os/android/adb/perfetto.go
Labels: cla: yes

#2842 Yet another fix for taking a perfetto trace on desktop.
  core/app/layout/layout.go
Labels: cla: yes

#2843 Stop outputting every file we copy from remote.
  core/os/device/remotessh/commands.go
Labels: cla: yes

#2836 Fix link URL
  tut-shaderiterating.md
Labels: cla: yes

#2844 Fix Perfetto help text.
  cmd/gapit/flags.go
Labels: cla: yes

#2848 Android: Pass GAPID argument --gapir-args from gapis to gapir
  cmd/gapir/cc/main.cpp
  cmd/gapis/main.go
  core/cc/log.cpp
  core/cc/log.h
  gapil/runtime/cc/runtime.cpp
  gapir/client/client.go
  gapir/client/session.go
Labels: cla: yes

#2851 Stop passing the GAPID version as a compiler flag.
  cmd/gapir/cc/BUILD.bazel
  cmd/gapir/cc/main.cpp
  core/cc/BUILD.bazel
  core/cc/version.h.in
  tools/build/rules/cc.bzl
  version.bzl
Labels: cla: yes

#2849 GLES API: Init framebuffer image data with proper slices
  gapis/api/gles/api/framebuffer.api
  gapis/api/gles/gles.api
Labels: cla: yes

#2853 New Tab UI.
  gapic/res/icons/fullscreen.png
  gapic/res/icons/fullscreen@2x.png
  gapic/res/icons/fullscreen_exit.png
  gapic/res/icons/fullscreen_exit@2x.png
  gapic/src/main/com/google/gapid/GraphicsTraceView.java
  gapic/src/main/com/google/gapid/MainWindow.java
  gapic/src/main/com/google/gapid/models/Settings.java
  gapic/src/main/com/google/gapid/widgets/TabArea.java
  gapic/src/main/com/google/gapid/widgets/TabComposite.java
  gapic/src/main/com/google/gapid/widgets/Theme.java
Labels: cla: yes

#2860 Dispose the widget when removing a tab.
  gapic/src/main/com/google/gapid/widgets/TabComposite.java
Labels: cla: yes

#2856 Fix tracing of Vulkan replay from archive
  core/memory_tracker/cc/memory_tracker.h
  gapir/cc/android/asset_resource_cache.cpp
Labels: cla: yes

#2866 Update the notification RPC to map its ID to a notification reader.
  gapir/cc/android/asset_replay_service.h
  gapir/cc/archive_replay_service.h
  gapir/cc/context.cpp
  gapir/cc/grpc_replay_service.cpp
  gapir/cc/grpc_replay_service.h
  gapir/cc/replay_service.h
  gapir/replay_service/service.proto
  gapis/api/vulkan/find_issues.go
  gapis/api/vulkan/query_timestamps.go
  gapis/replay/asm/instructions.go
  gapis/replay/builder/builder.go
Labels: cla: yes

#2865 Fix logging by using vprint() style log function
  core/cc/log.cpp
  gapii/cc/spy.cpp
Labels: cla: yes

#2872 Add dependencies between draw calls
  gapis/api/gles/api/draw_commands.api
  gapis/api/gles/api/egl.api
  gapis/api/gles/api/framebuffer.api
  gapis/api/gles/api/programs_and_shaders.api
Labels: cla: yes

#2874 Disable the horizontal mouse wheel in the Perfetto view.
  gapic/src/main/com/google/gapid/perfetto/TraceView.java
Labels: cla: yes

#2876 Don't dispose tabs when moving between folders.
  gapic/src/main/com/google/gapid/GraphicsTraceView.java
  gapic/src/main/com/google/gapid/widgets/TabComposite.java
Labels: cla: yes

#2888 Improve resource cache prefetch logging
  gapir/cc/resource_cache.cpp
Labels: cla: yes

#2886 Fix bug in texture view when selecting adjacent commands. (#2834)
  gapic/src/main/com/google/gapid/views/TextureView.java
Labels: GAPIC, bug, cla: yes

#2833 Shader View improvement
  gapic/res/icons/more.png
  gapic/res/icons/more@2x.png
  gapic/src/main/com/google/gapid/models/Settings.java
  gapic/src/main/com/google/gapid/views/ShaderView.java
  gapic/src/main/com/google/gapid/widgets/SearchBox.java
  gapic/src/main/com/google/gapid/widgets/Theme.java
Labels: GAPIC, cla: yes, enhancement
