Repository google/gapid, pull requests merged in 2019-07, with the labels that each got.

#2898 Fix a NPE in the trace target selection dialog.
  gapic/src/main/com/google/gapid/views/TraceTargetPickerDialog.java
Labels: cla: yes

#2900 Fix crash when building with -c opt
  cmd/gapir/cc/main.cpp
Labels: cla: yes

#2895 Fix adb screen test
  core/os/android/adb/adb_data_test.go
Labels: cla: yes

#2893 Fix compat test by adding necessary commands to hand-made capture
  gapis/api/gles/compat_test.go
Labels: cla: yes

#2881 Update the Command Tree for Vulkan.
  cmd/gapit/benchmark.go
  cmd/gapit/commands.go
  cmd/gapit/flags.go
  cmd/smoketests/main.go
  gapic/src/main/com/google/gapid/models/ApiContext.java
  gapic/src/main/com/google/gapid/util/Paths.java
  gapis/api/cmd_flags.go
  gapis/api/templates/api.go.tmpl
  gapis/api/vulkan/api/queue.api
  gapis/resolve/command_tree.go
  gapis/resolve/events.go
  gapis/service/path/path.proto
  gapis/service/service.proto
Labels: cla: yes

#2903 Unlock screen when starting a new replay session
  gapir/client/session.go
Labels: cla: yes

#2880 Add support for template generated go and cpp file
  cmd/gofuse/main.go
Labels: cla: yes

#2907 GLES API: Add missing update of texture ImmutableLevels field
  gapis/api/gles/api/textures_and_samplers.api
Labels: cla: yes

#2909 Add Android device setup advice
  trace.md
Labels: cla: yes

#2911 Fix Vulkan constants not showing up in the state tree.
  gapil/template/constant_sets.go
Labels: cla: yes

#2906 Update read/write to have relevant dependency for textured cube app
  gapis/api/gles/api/draw_commands.api
  gapis/api/gles/api/textures_and_samplers.api
Labels: cla: yes

#2916 Check if glReadPixels caused a GL error in on device replay.
  gapis/api/gles/read_framebuffer.go
Labels: cla: yes

#2894 Fix memory tracker destructor logic
  core/memory_tracker/cc/memory_tracker.h
  core/memory_tracker/cc/posix/memory_tracker.inc
Labels: cla: yes

#2921 Change executable path detection(#2879)
  cmd/gapid/main.go
Labels: cla: yes

#2930 Fix a bug in notification instruction
  gapir/cc/context.cpp
  gapis/api/vulkan/find_issues.go
  gapis/api/vulkan/query_timestamps.go
  gapis/replay/asm/instructions.go
  gapis/replay/builder/builder.go
Labels: cla: yes

#2926 Add PreLoop and PostLoop to the Transformer interface
  gapis/api/gles/replay.go
  gapis/api/sync/sync.go
  gapis/api/transform/capture_log.go
  gapis/api/transform/early_terminator.go
  gapis/api/transform/file_log.go
  gapis/api/transform/injector.go
  gapis/api/transform/tasks.go
  gapis/api/transform/transformer.go
  gapis/api/transform/transforms.go
  gapis/api/vulkan/overdraw.go
  gapis/api/vulkan/query_timestamps.go
  gapis/api/vulkan/read_framebuffer.go
  gapis/api/vulkan/replay.go
  gapis/api/vulkan/vulkan_terminator.go
  gapis/replay/batch.go
  gapis/replay/end_of_replay.go
  gapis/replay/mapping_printer.go
  gapis/resolve/dependencygraph/dead_code_elimination.go
  gapis/resolve/dependencygraph2/dce.go
Labels: cla: yes

#2933 Complete VK_EXT_debug_utils extension definition
  gapii/cc/vulkan_extras.inc
  gapis/api/vulkan/custom_replay.go
  gapis/api/vulkan/extensions/ext_debug_utils.api
Labels: cla: yes

#2938 Add clear link to source code repo
  about.md
Labels: cla: yes, docs

#2941 Fix typo
  gapis/api/transform/transformer.go
Labels: cla: yes

#2940 Fix compilation issue in transformer/injector_test.go
  gapis/api/transform/recorder.go
Labels: cla: yes

#2934 Add kokoro configuration for running tests on Kokoro.
  kokoro/linux-test/common.cfg
  kokoro/linux-test/continuous.cfg
  kokoro/linux-test/presubmit.cfg
  kokoro/linux-test/release.cfg
  kokoro/linux-test/test.sh
Labels: cla: yes

#2948 Add the test to the new kokoro test pipeline
  kokoro/linux-test/common.cfg
  kokoro/linux-test/continuous.cfg
  kokoro/linux-test/presubmit.cfg
  kokoro/linux-test/release.cfg
  kokoro/linux-test/test.sh
Labels: cla: yes

#2946 Fix typos in error messages
  tools/build/cc_toolchain.bzl
Labels: cla: yes

#2845 Update imagePrimer to support prime by copying from device image data.
  gapis/api/vulkan/image_primer_device_copy.go
  gapis/api/vulkan/image_primer_render.go
  gapis/api/vulkan/primeable_image_data.go
  gapis/api/vulkan/state_rebuilder.go
Labels: cla: yes

#2949 Fix dependency between glGenVertexArrays() and glBindVertexArray()
  gapis/api/gles/api/vertex_arrays.api
Labels: cla: yes

#2896 Fix stacktrace test
  core/assert/slice.go
  core/fault/stacktrace/stacktrace_test.go
Labels: cla: yes

#2951 Add dependencies for blending
  gapis/api/gles/api/draw_commands.api
Labels: cla: yes

#2954 Work around instance issues in a new way.
  gapir/cc/context.cpp
  gapir/cc/linux/vulkan_renderer.cpp
  gapir/cc/vulkan_gfx_api.inc
  gapis/api/templates/vulkan_gfx_api_extras.tmpl
  gapis/api/vulkan/custom_replay.go
  gapis/api/vulkan/synthetic.api
Labels: cla: yes

#2959 Do not crash if we have a missing shader.
  gapis/api/vulkan/resources.go
Labels: cla: yes

#2969 Split test targets to work around Kokoro OOM
  BUILD.bazel
  kokoro/linux-test/test.sh
Labels: cla: yes

#2968 Removed tutorial page; kept TOC entry
  _includes/sidebar.html
  tutorial.md
Labels: cla: yes

#2971 Revert "Removed tutorial page; kept TOC entry"
  _includes/sidebar.html
  tutorial.md
Labels: cla: yes

#2966 Refactoring the createBuffer in state rebuilder.
  gapis/api/vulkan/state_rebuilder.go
Labels: cla: yes

#2905 Initial work on getting Struct representations into the server.
  BUILD.bazel
  gapic/src/main/BUILD.bazel
  gapis/api/BUILD.bazel
  gapis/api/cmd_service.go
  gapis/api/gles/BUILD.bazel
  gapis/api/gvr/BUILD.bazel
  gapis/api/service.proto
  gapis/api/templates/BUILD.bazel
  gapis/api/templates/api.go.tmpl
  gapis/api/templates/api_memory_box.go.tmpl
  gapis/api/templates/api_types.go.tmpl
  gapis/api/vulkan/BUILD.bazel
  gapis/resolve/BUILD.bazel
  gapis/resolve/resolve.go
  gapis/service/BUILD.bazel
  gapis/service/memory_box/BUILD.bazel
  gapis/service/memory_box/box.go
  gapis/service/memory_box/box.proto
  gapis/service/memory_box/doc.go
  gapis/service/path/path.go
  gapis/service/path/path.proto
  gapis/service/path/validate.go
  gapis/service/service.go
  gapis/service/service.proto
  gapis/service/types/BUILD.bazel
  gapis/service/types/types.go
  gapis/service/types/types.proto
Labels: cla: yes

#2974 Make cmd/gapid prefer java in JAVA_HOME over PATH
  cmd/gapid/main.go
Labels: cla: yes, needs discussion

#2973 Make sure to touch all pages, in replay APK capture logic
  gapir/cc/android/asset_resource_cache.cpp
Labels: cla: yes

#2979 Read all levels and layers of texture to support e.g. mipmap
  gapis/api/gles/api/draw_commands.api
Labels: cla: yes

#2981 Add scissor test dependency to glClear
  gapis/api/gles/api/draw_commands.api
  gapis/api/gles/api/framebuffer.api
Labels: cla: yes

#2989 Make GAPIC build/run with JDK 11.
  tools/build/third_party/gapic_third_party.BUILD
  tools/build/workspace_gapic.bzl
Labels: cla: yes

#2992 Improve ordering of GAPID docs by manually constructing the TOC.
  _data/nav.yml
  _includes/nav.html
  _includes/sidebar.html
  assets/sidebar.scss
Labels: cla: yes

#2991 Loop the trace to get timestamps
  cmd/gapit/flags.go
  cmd/gapit/profile.go
  gapis/api/vulkan/BUILD.bazel
  gapis/api/vulkan/frame_loop.go
  gapis/api/vulkan/image_primer_host_copy.go
  gapis/api/vulkan/query_timestamps.go
  gapis/api/vulkan/replay.go
  gapis/api/vulkan/state_rebuilder.go
  gapis/replay/builder/builder.go
  gapis/replay/interfaces.go
  gapis/replay/timestamps.go
  gapis/server/export_replay.go
  gapis/server/server.go
  gapis/service/service.proto
Labels: cla: yes

#2993 Remove deprecated sidebar front matter from content files.
  about.md
  cli.md
  commands-pane.md
  framebuffer-pane.md
  geometry-pane.md
  inspect.md
  report-pane.md
  requirements.md
  shaders-pane.md
  state-pane.md
  textures-pane.md
  trace.md
  tut-capture-trace.md
  tut-create-video.md
  tut-exportresources.md
  tut-find-largest-textures.md
  tut-optimize.md
  tut-shaderbound.md
  tut-shaderiterating.md
  tut-vulkan-render-state.md
  tutorial.md
Labels: cla: yes

#2996 Update the Eclipse set up tutorial in GAPIC READ.ME.
  gapic/readme.md
Labels: cla: yes

#3001 Remove tutorials sub-landing page at https://gapid.dev/tutorials per b/137296027
  tutorial.md
Labels: cla: yes

#2990 Gapir LRU/prefetch replay cache with custom memory allocator
  cmd/gapir/cc/main.cpp
  gapir/cc/BUILD.bazel
  gapir/cc/android/asset_resource_cache.cpp
  gapir/cc/android/asset_resource_cache.h
  gapir/cc/cached_resource_loader.cpp
  gapir/cc/context.cpp
  gapir/cc/context_test.cpp
  gapir/cc/grpc_replay_service.cpp
  gapir/cc/in_memory_resource_cache.cpp
  gapir/cc/in_memory_resource_cache.h
  gapir/cc/in_memory_resource_cache_test.cpp
  gapir/cc/interpreter_test.cpp
  gapir/cc/memory_allocator.cpp
  gapir/cc/memory_allocator.h
  gapir/cc/memory_allocator_test.cpp
  gapir/cc/memory_manager.cpp
  gapir/cc/memory_manager.h
  gapir/cc/memory_manager_test.cpp
  gapir/cc/on_disk_resource_cache.cpp
  gapir/cc/on_disk_resource_cache.h
  gapir/cc/replay_request_test.cpp
  gapir/cc/resource.cpp
  gapir/cc/resource.h
  gapir/cc/resource_cache.cpp
  gapir/cc/resource_cache.h
  gapir/cc/resource_loader.h
  gapir/cc/resource_loader_test.cpp
  gapir/cc/stack_test.cpp
  gapir/cc/test_utilities_test.cpp
Labels: cla: yes
